# Generated by Django 4.1.7 on 2023-03-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0004_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='info',
            name='status',
            field=models.CharField(default='در دسترس', max_length=20),
        ),
    ]
